### ISSUE TITLE
upgrade to 0.7.2 caused desync of key filename and gitolite.conf

### ISSUE THREAD

**Issue by pva** [jbox-web/redmine_git_hosting#205]
Hello. After upgrade to 0.7.2 repositories access somehow get out of sync: in gitolite-admin I have my key in keydir/redmine_pva_1378383344_707089.pub, but in conf/gitolite.conf I'm named redmine_pva. Thus access to all repositories for me is blocked and whenever I do 
ssh -p 22222  git@dev.tightvideo.com I see:

```
hello redmine_pva_1378383344_707089, this is git@redmine running gitolite3 gitolite-3.6 on git 1.8.5.5

 R W    testing
```

I've tried to sync this back with "Resync all SSH keys" but it fails and I see following in logs:

```
2014-05-30 02:35:45 +0400 INFO [GitWorker] Using Gitolite configuration file : 'gitolite.conf'
2014-05-30 02:35:45 +0400 INFO [GitWorker] update_all_ssh_keys_forced : SSH key 'redmine_pva_1378383344_707089@' does not exist in Gitolite, create it ...
2014-05-30 02:35:45 +0400 INFO [GitWorker] update_all_ssh_keys_forced : commiting to Gitolite...
2014-05-30 02:35:45 +0400 ERROR [GitWorker] undefined method `empty?' for nil:NilClass
2014-05-30 02:35:45 +0400 INFO [GitWorker] update_all_ssh_keys_forced : SSH key 'redmine_dtokarev_1379072263_287370@' does not exist in Gitolite, create it ...
2014-05-30 02:35:45 +0400 INFO [GitWorker] update_all_ssh_keys_forced : commiting to Gitolite...
2014-05-30 02:35:45 +0400 ERROR [GitWorker] undefined method `empty?' for nil:NilClass
```

Could you help me here? How to debug this undefined method error?
